### PR TITLE
I added the username argument to the functions, and created an example to pull the post_id from a url.

### PR DESCRIPTION
**Pull request by FastFingertips**

### CODE REVIEW

**Comment by dmytrostriletskyi** [comment]
Thank you for the help with the codebase. 👍 

But to be honest, I do not like an approach to accept both username and integer (but required to specify either) because now instead of atomic and small functions (get threads, replies, and so on that require a user identity) we get side effects inside them (if username is provided, fetch an ID then).

I like the approach that we require an ID only and to fetch it, just use `get_user_by_username`.  Then the codebase is simpler and seems it is good approach because even `instagrapi` (library the project is based on ) does the same — https://github.com/adw0rd/instagrapi#basic-usage

What do you think?

**Comment by FastFingertips** [comment]
Yes I agree with you. Actually the input can be taken as id if int and username if str. this way it will be under a single variable. I was going to try this before, but usernames can be digits too.

**Comment by dmytrostriletskyi** [comment]
Thank you for the help! 👍

**Comment by dmytrostriletskyi** [comment]
Can you create a separate PR with just adding your method to get a post ID from URL into the `main.py` already? Not like example so we can merge your work then as normal.

**Comment by dmytrostriletskyi** [comment]
https://github.com/dmytrostriletskyi/threads-net/commit/c89bf9c71ba17bc24ed4a55fc5407f91a4c54aa3
https://github.com/dmytrostriletskyi/threads-net/commit/11210dab5a5862e7dadebb9138c7503e1f89cad4

Very big thanks to you for all the help you have done.

Please, in the future, just create production-ready PR with contributing into `main.py` so I can easily merge the code. If you just provide an example, it is hard to leave any review or negotiate.

**Pull request closed without merging**
