### PR TITLE
support get_user_followers, following for >100 users

### PR DESCRIPTION
**Pull request by theREalpha**
fixes issue #24 

Added support for retrieving more than 100 users from the private APIs get_user_followers and get_user_following.

**Description**
The pull request modifies the private APIs to check for the presence of 'next_max_id' in the response. If it exists, it makes a new request with the 'next_max_id' as 'max_id' as a parameter, otherwise it returns the list of users. 
The API takes user_id as input (no change), and returns a python list of users following or followed by the user_id.

### CODE REVIEW

**Comment by dmytrostriletskyi** [comment]
Thanks for the PR! 👍 

I will check soon.

**Comment by dmytrostriletskyi** [comment]
@theREalpha, yeah, I agree with @maksam07 concerns. The best practice and most commonly used approach is to provide `limit` and `offset` arguments, so users can go like:

```
get_user_followers(id=7918764, limit=20, offset=20)
get_user_followers(id=7918764, limit=20, offset=40)
get_user_followers(id=7918764, limit=20, offset=60)
```

Like as it is done in `RESTful APIs`, for instance, or `SQL Queries`. Then users have more control on the flow and can rely on their rate limits better.

**Comment by theREalpha** [comment]
Each request results in max 100 users in its response. So setting `limit` and `offset` to multiples of 100 would be a better choice.

The first `max_id` in that case would be the `offset`, and `limit` can be achieved by substracting no. of users in response with each request and stopping once it reaches 0 or negative.  Something of the essence 

```
def get_user_followers(self, id: int, limit: int, offset: int) :

    followers = [ ]

    if offset:
        max_id = offset
    else: 
        resp = requests.get(url,headers).json()
        followers.extend(resp.get('users'))
        max_id = resp.get('next_max_id')

    while max_id and limit > 0:
        resp = requests.get(url,headers, params = {'max_id': max_id}).json()
        limit -= resp.get('length')         
        followers.extend(resp.get('users'))
        max_id = resp.get('next_max_id')

    return followers
```


For offsets lower than 100, I need to verify if max_id is the index of first user from where we want the rest of the list or is some other quantity altogether like 'page_id'. I'll look into it after the login API is working again.

**Comment by theREalpha** [comment]
looks like friendship API changed, the response no longer has 'next_max_id' for offset and doesn't accept 'count' as a parameter for limit and returns 50 users always

example request and response

```
resp=requests.get(
    url=f'{INSTAGRAM_API_URL}/friendships/{ibm}/followers/', headers, 
    params = {'count':150}
    ).json()
```
```
{'users': ["list of 50"],
 'big_list': False,
 'page_size': 200,
 'has_more': False,
 'should_limit_list_of_followers': False,
 'status': 'ok'}
```

**Comment by dmytrostriletskyi** [comment]
Thanks for the work. When I have time, I dive into it. Want to investigate it practically and deeper, as it might be a core logic for many other endpoints as well.

**Comment by theREalpha** [comment]
I've added the base logic for `limit`, `offset` and I had to add a `rank_token`  using uuid to `params`, to make sure the order of list remains the same across requests. Hope this helps a bit. 

I'll close the PR for now.

**Pull request closed without merging**
